package ShoppingCartGUI;

import ShoppingCartClient.ShoppingCart;
import ShoppingCartClient.*;
import java.awt.FlowLayout;
import java.awt.event.ActionListener;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Group 31
 */
public class SellerView extends javax.swing.JFrame {
    /**
     * Creates new form SellerView
     */
    public SellerView() {
        initComponents();
    }

    /**
     * Adds JLabels for the profit, revenue, and invoice. Gets the information from the seller and displays it.
     */
    public void profits()
    {
        ShoppingCart.currentSeller.calcInvoice();
        profitL = new JLabel("Profit: $" + Double.toString(ShoppingCart.currentSeller.getProfit()));
        revenueL = new JLabel("Revenue: $" + Double.toString(ShoppingCart.currentSeller.getRevenue()));
        costL = new JLabel("Invoice: $" + Double.toString(ShoppingCart.currentSeller.getInvoice()));
        profitL.setVisible(true);
        revenueL.setVisible(true);
        costL.setVisible(true);
        jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));
        jPanel3.add(profitL);
        jPanel3.add(revenueL);
        jPanel3.add(costL);
        
        
    }

    /**
     * Displays all of the products for the seller. Adds buttons and action listeners so 
     * the seller can update the inventory, remove products, and add new products
     * @param s current seller
     */
    public void showProducts(Seller s)
    { 
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
        for(Item p: s.getSInventory())
        {
            JPanel panel = new JPanel();
            panel.setLayout((new FlowLayout(FlowLayout.LEFT)));
            JLabel pID = new JLabel("ID: " + Integer.toString(p.getID()));
            JLabel pName = new JLabel("Name: " + p.getName());
            JLabel pQ = new JLabel("Quantity: ");
            JTextField jField = new JTextField(Integer.toString(p.getQuantity()), 3);
            JButton details = new JButton("Details");
            JButton update = new JButton("Update");
            JCheckBox bundle = new JCheckBox("Bundle");
            //Updates quantity from the text box when update is clicked
            update.addActionListener(new ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    try
                    {
                        Integer q;
                        q = Integer.parseInt(jField.getText());
                        p.setQuantityPurchased(q);
                        refreshPage();
                    }
                    catch(IllegalArgumentException e)
                    {
                        JOptionPane.showMessageDialog(null, "Invalid input");
                    }
                }
            });
            
            //Displays item details whe details is clicked
            details.addActionListener(new ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    JOptionPane.showMessageDialog(null,p.getDetails(), "Product Details", JOptionPane.INFORMATION_MESSAGE);
                }
            });
            JButton remove = new JButton("Remove");
            
            //Completely removes item when remove is clicked
            remove.addActionListener(new ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    s.RemoveProduct(p);
                    refreshPage();
                    
                }
            });
            panel.add(pID);
            panel.add(pName);
            panel.add(pQ);
            panel.add(jField);
            panel.add(update);
            panel.add(details);
            panel.add(remove);
            panel.add(bundle);

            jPanel2.add(panel);
            //jPanel2.add(Box.createVerticalStrut(2));
        }    
    }
    
    /**
     * Updates window if information is changed
     */
    public void refreshPage()
    {
        jPanel2.removeAll();
        jPanel3.removeAll();
        ShoppingCart.openSHome(this.getX(), this.getY());
        ShoppingCart.currentSeller.calcInvoice();
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(608, 470));

        jLabel1.setText("Home");

        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add new Item");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton3.setText("Create Bundle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/**
 * Makes pop-up box for adding a new product when clicked
 * @param evt event handler for clicking the button
 */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AddPView pv = new AddPView();
        pv.setLocation(this.getX()+59, this.getY()+40);
        pv.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * Signs out when the button is clicked
     * @param evt event handler for clicking the button
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //refreshPage();
        jPanel2.removeAll();
        jPanel3.removeAll();
        ShoppingCart.setCurrentSeller(null);
        ShoppingCart.openLogin(this.getX(),this.getY()); 
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Creates a bundle from the items that are checked when clicked
     * @param evt event handler for clicking buttons
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Bundle bundle = new Bundle(1);
        int i =0;
        //Checks if the checkbox is checked
        for(Item item: ShoppingCart.currentSeller.getSInventory())
        {
            JPanel p = (JPanel) jPanel2.getComponent(i);
            JCheckBox b = (JCheckBox) p.getComponent(7); //CheckBox is componenty 7
            JLabel id = (JLabel) p.getComponent(1);
            //Adds the item to the bundle
            if(b.isSelected())
            {
                bundle.add(item);
            }
            i++;
        }
        //Discounts the bundle by 10%
        DiscountItem d = new DiscountItem(bundle, 10);
        ShoppingCart.currentSeller.getSInventory().add(d);
        refreshPage();
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JLabel profitL;
    private javax.swing.JLabel revenueL;
    private javax.swing.JLabel costL;  
}